### ISSUE TITLE
SPEED DATE TIME ATTRIBUTES IN THIS LIBRARY

### ISSUE THREAD

**Issue by gopalakartkikeyan** [gmag11/WifiLocation#11]
Hi,

 Will u please add all the attributes like lat, long,speed,altitude,date time etc in this library.

**Comment by gmag11** [comment]
Google only gives latitude, longitude and accuracy. Speed and altitude requires a real GPS receiver.
You can get date and time from internal ESP8266/ESP32 api. Indeed, time is synchronised before google api request do that HTTPS works correctly.

**Comment by gmag11** [comment]
I close the issue. Feel free to ask more information if you like to.
