### ISSUE TITLE
Incorrect locating after changing the position of the device

### ISSUE THREAD

**Issue by bfaliszek** [gmag11/WifiLocation#12]
Thanks for sharing the code. It works very well and I have no major problems with it.

I only noticed that after locating ESP32 in a one place and moving it elsewhere (e.g. a dozen kilometers away), for the first 24-48 hours Google API still returns the coordinates of the previous location. I don't know if it's related to the code itself (rather not), or it's Google API's fault.

**Comment by KCerveny** [comment]
It may be part of the API body. Try changing "considerIp:" to false and see if your results will change.

**Comment by gmag11** [comment]
I've added @KCerveny suggestion in version 1.2.8 (86bc60332c3ee075ce441258965b825fe1ac5b7f). Please @bfaliszek , check if it fixes your issue
