### ISSUE TITLE
Esp32 - Unkown Error

### ISSUE THREAD

**Issue by Esteves4** [gmag11/WifiLocation#13]
I'm using an Esp32 and an error kept showing up:

_handle_error(): [data_to_read():270]: (-80) UNKNOWN ERROR CODE (0050)

I found that the code 0050 meant that the server were closing the connection, so, I changed the HTTP header in line 120 to keep the conection alive -> "request += "Connection: keep-alive\r\n\r\n";"

Don't know which impacts this may cause, but it fix it for me.

**Comment by gmag11** [comment]
Hi. did it work for you? Makes sense. Please add a pull request if so.

**Comment by gmag11** [comment]
Fixed on 20a860717d1e38a385754675d9b8e843a3118ec6 using @Esteves4 proposal
