### ISSUE TITLE
_nomap and hidden APs

### ISSUE THREAD

**Issue by bertrik** [gmag11/WifiLocation#14]
Do you honour to omit APs with the following properties:
* APs with "_nomap" in their name
* hidden APs
?

See for example: https://www.androidpolice.com/2020/05/03/opt-out-wi-fi-from-google-location-services/

**Comment by gmag11** [comment]
Hi. This library only makes use of BSSID, so all APs found are sent, including _nomap and hidden APs. I understand that it is Google's responsibility to filter out all networks that they detected as opt-out during their data collection.

**Comment by bertrik** [comment]
I think this borders on negligence. AP owners are indicating they do not wish to be mapped, there is a de-facto mechanism for that, and this library knowingly ignores it.

This library *does* have access to the SSIDs and whether an AP is hidden. When you submit the data to google (or some other geolocation provider), that information is stripped, so even they cannot know anymore that the AP should not be mapped.

**Comment by gmag11** [comment]
This library does not send neither check any SSID, only BSSID's. It does not map anything. Android phones are the ones who collect all that data and it is Google's responsibility to filter out those APs.

**Comment by bertrik** [comment]
You seem to misunderstand my point, I am not asking if you send the SSID ("AP name") to google. However, if you send 10 MAC addresses, of which 9 are "normal" and 1 has the "_nomap" indicator, it is trivial to figure out where that "nomap" device is located (which is, somewhere close to the other 9 devices), against the wishes of the AP owner. So, by submitting them too, you are actually actively helping to map these "nomap" devices. 

If my point is not clear yet, I can perhaps elaborate on the explanation, please let me know.
It would be nice if you could describe this behaviour in your documentation.

**Comment by gmag11** [comment]
Hi I get the point. I'll try to implement that behaviour on next version. Thanks
