### ISSUE TITLE
Compile error in WifiLocation.cpp

### ISSUE THREAD

**Issue by yashm** [gmag11/WifiLocation#17]
Compiling results in the following error:

WifiLocation\src\WifiLocation.cpp:73:68: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'uint8_t*' {aka 'unsigned char*'} [-fpermissive]

**Comment by gmag11** [comment]
Hi, May you copy your WiFiLocation.cpp here? Line 73 in repository does not have code so I cannot identify what can be the matter.
