### ISSUE TITLE
Again HTTPS error with new Certificate

### ISSUE THREAD

**Issue by richie241** [gmag11/WifiLocation#19]
Hi,

after a few days with the new certificate it worked wonderfully, now the old error appears again. Was something else adjusted here on the part of google?

16:17:17.342 -> Waiting for NTP time sync: 
16:17:17.342 -> Current time: Mon Aug 23 14:17:18 2021
16:17:17.792 -> HTTPS error
16:17:17.792 -> Location request data
16:17:19.367 -> 8 WiFi networks found
16:17:19.367 -> WiFi list:
16:17:19.367 -> [{"macAddress":"-","signalStrength":-62,"channel":6},
16:17:19.412 -> {"macAddress":"-","signalStrength":-87,"channel":6},
16:17:19.412 -> {"macAddress":"-","signalStrength":-73,"channel":6},
16:17:19.412 -> {"macAddress":"-","signalStrength":-43,"channel":6},
16:17:19.412 -> {"macAddress":"-","signalStrength":-89,"channel":6},
16:17:19.412 -> {"macAddress":"-","signalStrength":-79,"channel":6},
16:17:19.412 -> {"macAddress":"-","signalStrength":-87,"channel":6},
16:17:19.412 -> {"macAddress":"-","signalStrength":-87,"channel":11}]
16:17:19.457 -> 
16:17:19.457 -> [{"macAddress":"-","signalStrength":-62,"channel":6},
16:17:19.457 -> {"macAddress":"-","signalStrength":-87,"channel":6},
16:17:19.457 -> {"macAddress":"-","signalStrength":-73,"channel":6},
16:17:19.457 -> {"macAddress":"-","signalStrength":-43,"channel":6},
16:17:19.457 -> {"macAddress":"D-","signalStrength":-89,"channel":6},
16:17:19.457 -> {"macAddress":"-","signalStrength":-79,"channel":6},
16:17:19.457 -> {"macAddress":"-","signalStrength":-87,"channel":6},
16:17:19.457 -> {"macAddress":"-","signalStrength":-87,"channel":11}]
16:17:19.502 -> Location: 0.0000000,0.0000000
16:17:19.502 -> Accuracy: 40000
16:17:19.502 -> Result: API connection error

**Comment by gmag11** [comment]
Maybe googled is playing with certificates.

You can update certificate by yourself.

I extract this text from Readme.md

-------------------------------------

You may get current certificate using this command (if you are using Linux)

```
openssl s_client -servername www.googleapis.com -showcerts \
 -connect www.googleapis.com:443 < /dev/null \
 |  awk '/^-----BEGIN CERTIFICATE-----/,/^-----END CERTIFICATE-----/{if(++m==1)n++;if(n==2)print;if(/^-----END CERTIFICATE-----/)m=0}' \
 > googleCA.cer
```

Then, you can copy file content and overwrite this part of WifiLocation.cpp, from line 14.
-------------------------------------

I'll check it anyway

**Comment by gmag11** [comment]
They are using the old certificate again. This is the one that expires on December 21th so you can expect that it changes again. I hope it will be stable afterwards.

Current certificate is this:

```
-----BEGIN CERTIFICATE-----
MIIESjCCAzKgAwIBAgINAeO0mqGNiqmBJWlQuDANBgkqhkiG9w0BAQsFADBMMSAw
HgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMjETMBEGA1UEChMKR2xvYmFs
U2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjAeFw0xNzA2MTUwMDAwNDJaFw0yMTEy
MTUwMDAwNDJaMEIxCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVHb29nbGUgVHJ1c3Qg
U2VydmljZXMxEzARBgNVBAMTCkdUUyBDQSAxTzEwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDQGM9F1IvN05zkQO9+tN1pIRvJzzyOTHW5DzEZhD2ePCnv
UA0Qk28FgICfKqC9EksC4T2fWBYk/jCfC3R3VZMdS/dN4ZKCEPZRrAzDsiKUDzRr
mBBJ5wudgzndIMYcLe/RGGFl5yODIKgjEv/SJH/UL+dEaltN11BmsK+eQmMF++Ac
xGNhr59qM/9il71I2dN8FGfcddwuaej4bXhp0LcQBbjxMcI7JP0aM3T4I+DsaxmK
FsbjzaTNC9uzpFlgOIg7rR25xoynUxv8vNmkq7zdPGHXkxWY7oG9j+JkRyBABk7X
rJfoucBZEqFJJSPk7XA0LKW0Y3z5oz2D0c1tJKwHAgMBAAGjggEzMIIBLzAOBgNV
HQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBIGA1Ud
EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFJjR+G4Q68+b7GCfGJAboOt9Cf0rMB8G
A1UdIwQYMBaAFJviB1dnHB7AagbeWbSaLd/cGYYuMDUGCCsGAQUFBwEBBCkwJzAl
BggrBgEFBQcwAYYZaHR0cDovL29jc3AucGtpLmdvb2cvZ3NyMjAyBgNVHR8EKzAp
MCegJaAjhiFodHRwOi8vY3JsLnBraS5nb29nL2dzcjIvZ3NyMi5jcmwwPwYDVR0g
BDgwNjA0BgZngQwBAgIwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly9wa2kuZ29vZy9y
ZXBvc2l0b3J5LzANBgkqhkiG9w0BAQsFAAOCAQEAGoA+Nnn78y6pRjd9XlQWNa7H
TgiZ/r3RNGkmUmYHPQq6Scti9PEajvwRT2iWTHQr02fesqOqBY2ETUwgZQ+lltoN
FvhsO9tvBCOIazpswWC9aJ9xju4tWDQH8NVU6YZZ/XteDSGU9YzJqPjY8q3MDxrz
mqepBCf5o8mw/wJ4a2G6xzUr6Fb6T8McDO22PLRL6u3M4Tzs3A2M1j6bykJYi8wW
IRdAvKLWZu/axBVbzYmqmwkm5zLSDW5nIAJbELCQCZwMH56t2Dvqofxs6BBcCFIZ
USpxu6x6td0V7SvJCCosirSmIatj/9dSSVDQibet8q/7UK4v4ZUN80atnZz1yg==
-----END CERTIFICATE-----
```

**Comment by richie241** [comment]
Thank you - i hope google keeps changing the certificate back and forth so that the program is stable (until the end of 2021)

**Comment by gmag11** [comment]
Maybe certificate depends on the server that gets in charge of every request for googleapis.com. I hope this gets solved when old cert is expired.
I this happens too often I can program a version with two certificates but I guess it is not optimal
