### ISSUE TITLE
Download Location Data For Offline Use

### ISSUE THREAD

**Issue by OwensDataCenter** [gmag11/WifiLocation#20]
Download location data up to 1 mile*, When the ESP32/ESP8266 reconnects to WiFi in a different spot, The ESP will delete the previous download and redownload the updated data for a different area, Also having the option to connect to any open WiFi network** to download data when available.

Keep me updated on the results!

*User configurable, Minimum is .01 miles, Maximum is 1.00, Default is 1.00 (In code it would be 01 min, 10 max, 05=0.05 mi)
**User can also still use their own secure networks

This would need to be tested for full functionality.

**Comment by gmag11** [comment]
Hi. You cannot download any offline data from Google as it is not exposed neither the location calculation algorithm is public. What you expect is not a use case for this library.
