### ISSUE TITLE
I already solved my problem, "I did not have a billing account associated with the API project"

### ISSUE THREAD

**Issue by ALJastice25** [gmag11/WifiLocation#23]
I already solved my problem, "I did not have a billing account associated with the API project"

Connected
Waiting for NTP time sync: .
Current time: Sun Sep  5 06:22:12 2021
Location request data
[{"macAddress":"08:3E:0C:81:B0:D0","signalStrength":-84,"channel":8}]

Location: 4.5383682,-75.6908035
Accuracy: 3560
Result: OK

_Originally posted by @alejolopez03 in https://github.com/gmag11/WifiLocation/issues/10#issuecomment-913094233_

**Comment by ALJastice25** [comment]
Can i know how you fix yours because i tried all i've seen here and other site and the result are still the same 0.00000,0.0000
Thank you for respond.

**Comment by gmag11** [comment]
In case of problems you can enable logging in this line https://registry.platformio.org/libraries/gmag11/QuickDebug/installation

Just set it to 1
