### ISSUE TITLE
Return the names of the detected SSIDs

### ISSUE THREAD

**Issue by probonopd** [gmag11/WifiLocation#6]
It would be nice if ESPWifiLocation could return to the sketch the names of the detected SSIDs. My sketch, for example, needs to check for the presence of a certain SSID. Of course I could do just another scan in my sketch, but that is wasteful in terms of energy consumption and time needed since ESPWifiLocation is doing a scan already.

**Comment by gmag11** [comment]
You can use getSurroundingWiFiJson() bit internally it scans networks.

You may use WiFi.SSID(index) to get last scan result.

**Comment by probonopd** [comment]
Thank you. Maybe this could be documented/shown in an example sketch.
