### ISSUE TITLE
doesn't return correct values

### ISSUE THREAD

**Issue by aarons2222** [gmag11/WifiLocation#7]
displays this in the Serial Monitor

Latitude: 0.0000000
Longitude: 0.0000000
Accuracy: 40000

**Comment by gmag11** [comment]
This happens when any error occurs while requesting position to Google. Did you get a Google Maps API key? You may enable DEBUG traces by uncommenting [this line](https://github.com/gmag11/ESPWifiLocation/blob/master/src/WifiLocation.h#L12)
